/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  ignoredRouteFiles: ["**/.*"],
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: "build/index.js",
  // publicPath: "/build/",
  serverModuleFormat: "cjs",
  serverDependenciesToBundle: [
    "d3",
    /^d3-*/,
    "delaunator",
    "internmap",
    /^nanoid.*/,
    /^rehype.*/,
    /^remark.*/,
    /^unified.*/,
    /^unist.*/,
    /^hast.*/,
    /^bail.*/,
    /^trough.*/,
    /^mdast.*/,
    /^micromark.*/,
    /^decode.*/,
    /^character.*/,
    /^property.*/,
    /^space.*/,
    /^comma.*/,
    /^react-markdown$/,
    /^vfile.*/,
    /^ccount*/,
    /^markdown-table*/,
    /^longest-streak.*/,
    /^is-plain-obj.*/,
    /^escape-string-regexp.*/,
    /^trim-lines.*/,
    "axios",
  ],
  tailwind: true,
}
